'use client';
import {ArrowUpRight} from 'lucide-react';
import {PortfolioFinder} from './portfolio-finder';
import {DeepGridVisual} from './deepgrid-visual';
import {url} from './routes';
import {readHref} from './doc-links';
import {Workbench,SafetyWorkbench} from './portfolio-workbench';
import {EvaluationMatrix,QualificationRoute} from './portfolio-story';
import {claims} from './claims';
import {PortfolioV6Style} from './portfolio-v6-style';
import {ScrollAct} from './scroll-act';
const src=(s:string,section?:string)=>readHref('/downloads/'+s.replace(/^\/?downloads\//,''),section);
export function Overview({reduced}:{reduced:boolean}){return <div className="v6-home v11-home"><PortfolioV6Style/>
<section className="v11-hero" aria-labelledby="home-title"><div className="v11-hero-copy"><h1 id="home-title">Build the systems that<br/>move, protect and connect.</h1><p>DeepGrid is developing silicon for equipment makers in motion, power, sensing and communications. Find the product opportunity, then assess the evidence and work required for adoption.</p><div className="v11-actions"><a className="v11-button" href="#portfolio">Explore the product opportunity <ArrowUpRight size={18}/></a><a className="v11-text-link" href="#dg32-proof">Assess the evidence <ArrowUpRight size={18}/></a></div><div className="v11-evidence-note"><span>Architecture to evaluation</span><p>Pre-silicon portfolio. Design targets and engineering evidence, clearly distinguished.</p></div></div><DeepGridVisual kind="overview" priority/></section>
<section className="dgs-proof-strip" aria-label="Evidence at a glance"><ul><li><a href={url('/products')}><strong>12</strong><span>architectures</span><small>Pre-silicon portfolio · SKU Blueprint</small></a></li>{([['fault-39','injected fault to protective response'],['fmax-lockstep','lockstep core, sets the 50 MHz clock'],['node-130','process, for 28 to 120 V rails']] as const).map(([id,label])=>{const c=claims[id];return <li key={id}><a href={src(c.source)} title={c.measures}><strong>{c.figure}</strong><span>{label}</span><small>{c.kind} · {c.sourceTitle}</small></a></li>})}</ul></section>
<nav className="v11-application-strip" aria-label="Explore by application"><span>What are you building?</span>{[['Motors & drives','motors'],['Vehicles','vehicles'],['Defence & drones','defence'],['Grid & metering','grid'],['Board infrastructure','boards']].map(([name,path])=><a key={path} href={url('/use-cases/'+path)}>{name}</a>)}</nav>
<section className="v6-section" id="dg32-proof"><header><h2>Make fault response<br/>part of the customer evaluation.</h2><p>DG32 is designed to detect a processor disagreement and trigger a protective response without waiting for application software. The important decision is whether that response meets the needs of the complete machine.</p></header><ScrollAct span={4.5} className="dgs-fault-act">{progress=><SafetyWorkbench reduced={reduced} progress={progress}/>}</ScrollAct><div className="v6-proof"><strong>{claims['fault-39'].figure}</strong><div><b>Injected-fault response · simulated</b><p>The complete reported path differs from the checker’s two-cycle execution skew. Hardware lockstep is a mechanism, not a functional-safety certificate.</p><a href={src(claims['fault-39'].source)}>Read the fault-path source <ArrowUpRight size={14} aria-hidden="true"/></a></div></div><a className="v6-link" href={url('/technology/safety')}>Inspect fault causes and reset behaviour</a></section>
<section className="v6-section v6-diagnostics"><header><h2>Add diagnostics where<br/>they improve the product.</h2><p>Monitoring can help an equipment maker identify developing faults. It must fit around the primary control task and use signals good enough to support the intended decision.</p></header><p className="dgs-figure-title">At a 10 kHz control loop, 82 % of the core’s cycles stay free for diagnostics after the hardware datapath and the control firmware.</p><div className="v6-budget"><div><strong>177</strong><span>cycles · ADC acquisition</span></div><div><strong>53–58</strong><span>cycles · CORDIC</span></div><div><strong>≈300</strong><span>cycles · hardware datapath</span></div><div><strong>82%</strong><span>headroom at 10 kHz</span></div></div><div className="v6-roadmaps"><article><h3>Useful diagnosis starts with useful measurements.</h3><p>The 8-bit ADC can limit feature quality. Some applications need conditioning or external conversion. Headroom at 10 kHz is not headroom at the simulated ≈100 kHz loop ceiling.</p></article><article><h3>Add computing capacity only when the workload needs it.</h3><p>An INT8 attention engine operates across a clock-domain boundary. It does not raise the control-loop ceiling or replace the hardware safety path.</p></article></div><a className="v6-link" href={url('/technology/control-loop')}>Inspect the hardware / firmware time budget</a><a className="v6-link" href={url('/applications')}>Which diagnostic tasks fit the remaining cycles</a> <a className="v6-cite" href={src('deepgrid-dg32-ai-architecture.md')}>Source: DG32 AI architecture</a></section>
<PortfolioFinder/>
<section className="v11-system"><div className="v11-system-intro"><h2>Start with the system<br/>your customer needs.</h2><p>A product earns its place by solving a system problem. Explore how control, power and interfaces contribute to the equipment, and which responsibilities remain outside the chip.</p><a className="v11-text-link" href={url('/applications')}>Explore system applications</a><DeepGridVisual kind="products"/></div><Workbench reduced={reduced}/></section>
<section className="v6-section v6-bone"><header><h2>Stage the commitment<br/>against the evidence.</h2><p>An architecture can justify investigation; a production decision requires much more. Separate design validation, manufactured-silicon results and qualification in the evaluation plan.</p></header><QualificationRoute/><div className="v6-proof"><strong>198 days</strong><div><b>Analytic planning model · 30 digital + 168 physical days</b><figure className="dgs-split-bar" aria-label="198-day shuttle loop: 30 days of digital design, then 168 days of physical design and fabrication"><div className="dgs-split-track"><span style={{flexGrow:30}}><b>30</b> digital</span><span style={{flexGrow:168}}><b>168</b> physical</span></div><figcaption>Days, RTL to GDSII shuttle loop · analytic</figcaption></figure><p>This is a development model, not a demonstrated universal turnaround. Analog and high-voltage blocks can require additional silicon cycles.</p><a href={src('deepgrid-mature-silicon-architecture.md')}>Read the model and assumptions <ArrowUpRight size={14} aria-hidden="true"/></a></div></div><a className="v6-link" href={url('/evidence')}>Review published evidence and withheld claims</a></section>
<section className="v6-section v6-close"><header><h2>Define the opportunity.<br/>Agree the next milestone.</h2><p>Tell us the customer problem, target product and timing. We can scope an evaluation around the function you need and the evidence required for your next decision.</p></header><EvaluationMatrix/><div className="v6-actions"><a className="v6-primary" href={url('/contact')}>Discuss a system <ArrowUpRight size={18}/></a><a className="v6-link" href={url('/resources/docs')}>Review the supporting sources</a><a className="v6-link" href={url('/ask')}>Ask a business question</a></div></section>
</div>}


